# Copy to config.toml and adjust as needed

[server]
host = "0.0.0.0"
port = 8080

[paths]
cert = "certs/cert.crt"
key = "certs/cert.key"
# wallet_dir = "/custom/path/to/wallets"

[electrum]
command = "electrum-ltc"
